### ISSUE TITLE
ThreadPool with multiple threads and many tasks causes strange crashes

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#10]
ThreadPool.gd implements a pool of pre-started threads which work off a shared queue. The purpose is to be able to efficiently delegate work (such as LOD tile splitting) to these pre-started threads.

ThreadTest.gd stress-tests this implementation and results in very strange behavior.

With one thread (THREAD_COUNT = 1), everything seems to work, but when increasing this number, ThreadTest crashes with no error message. Giving it more tasks per tick in ThreadTest amplifies this behavior.

Strangely, the issue persists even when changing back to one thread - similar crashes occur until restarting the whole editor.

**Comment by kb173** [comment]
Possibly related to #11?

**Comment by kb173** [comment]
On Linux, the debugger shows:

```Condition 'idx == -1' is true.
Condition 'data.parent' is true.```

repeatedly, but in inconsistent intervals while running ThreadTest.

**Comment by kb173** [comment]
Sometimes - especially after having run the test multiple times previously - I get ` drivers/windows/stream_peer_tcp_winsock.cpp:203 - Server disconnected!` and the following errors as soon as the first task would be executed:

```
0:00:03:0731 - Condition ' !mem ' is true. returned: __null
----------
Type:Error
Description: 
Time: 0:00:03:0731
C Error: Condition ' !mem ' is true. returned: __null
C Source: core/os/memory.cpp:139
C Function: realloc_static

0:00:03:0733 - Condition ' !_ptrnew ' is true. returned: ERR_OUT_OF_MEMORY
----------
Type:Error
Description: 
Time: 0:00:03:0733
C Error: Condition ' !_ptrnew ' is true. returned: ERR_OUT_OF_MEMORY
C Source: core/vector.h:296
C Function: resize

0:00:03:0734 - Condition ' err ' is true. returned: true
----------
Type:Error
Description: 
Time: 0:00:03:0734
C Error: Condition ' err ' is true. returned: true
C Source: core/vector.h:355
C Function: push_back
```

At other times, especially when the crash occurs after running the test for a while, I simply get this in Godot's editor console:

```
Nothing read: Invalid argument
```

**Comment by chrisgraf** [comment]
Is this fixed with the new godot 3.1 beta?

**Comment by kb173** [comment]
@chrisgraf As of beta8, there are still crashes, although with different error messages. I've been trying to pinpoint exactly where it's coming from, but there's definitely something wrong somewhere in the engine code: The lines in the engine which are throwing the error have the comments `// should NOT happen.` and `// should really not happen either`... ([godot/arrray.cpp](https://github.com/godotengine/godot/blob/master/core/array.cpp) in `Array::_ref`)

Once I can locate the exact reason it's happening in our project, I will open another updated and more precise issue. I haven't been able to replicate it with simple example projects.

**Comment by kb173** [comment]
Closing this issue, since while these are some extremely ugly errors which should be changed in Godot itself, we seem to have figured out the cause and fixed it.

The main cause was changing resource variables and shader parameters from Threads. To fix this, the AbstractModule now makes it easy to load in multiple stages: First, everything that's safe to do in a Thread can be done in a Thread (this is mostly loading data from the server and the filesystem), and then (in the `_on_ready()` function, which is called from the main thread) this data can be applied.

**Comment by chrisgraf** [comment]
is there a issue in godot itself we could watch for this?

**Comment by kb173** [comment]
I don't think so... however, at this point we don't require a fix in Godot anways - it simply would've made it a lot easier to find these issues if there were actual error messages instead of the client crashing with obscure C++ engine errors with no documentation.

I do remember reading that this is something that they'd want to improve at some point, but is not a priority, since getting clean errors for Thread-unsafe operations is hard.
